[package]
name = "shipit"
version = "0.1.0"
authors = ["Carl Lerche <me@carllerche.com>"]
edition = "2018"

[dependencies]
clap = "2.32.0"
git2 = "0.8.0"
serde = "1.0.84"
serde_derive = "1.0.84"
toml = "0.4.10"
